name: "frontend workflow"

env:
    API_URL: https://api.edu-4.store/api
    IMAGE_NAME: front-session6

on:
    push:
        branches: 
          - main

jobs:    
    unit_testing:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: install dependencies
              run: npm i --force

            - name: run unit tests
              run: npm run test

    build_and_push:
        needs: unit_testing
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v4

            - name: build docker image
              run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}} --build-arg ${{env.API_URL}} .

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: push docker image to registry
              run: docker push ${{ vars.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}

            - name: "tag image"
              run: docker tag ${{ vars.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}} ${{ vars.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:${{ github.run_number }}

            - name: "push tagged image"
              run: docker push ${{ vars.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:${{ github.run_number }}

    deployment_job:
        runs-on: ubuntu-latest
        needs: [ "build_and_push" ]
        steps:
            - name: "ssh access to vps and deploy"
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                script: |
                    cd /home/user/devops-ecommerce/front
                    sudo git pull
                    sudo docker compose pull
                    sudo docker compose up -d --force-recreate --remove-orphans

    undeploy_job:
        runs-on: ubuntu-latest
        needs: [ "deployment_job" ]
        steps:
            - name: "ssh access to vps and deploy"
              uses: appleboy/ssh-action@v1.2.0
              with:
                host: ${{ secrets.VPS_HOST }}
                username: ${{ secrets.VPS_USERNAME }}
                password: ${{ secrets.VPS_PASSWORD }}
                script: |
                    cd /home/user/devops-ecommerce/front
                    PREVIOUS_RUN_NUMBER=$(( ${{ github.run_number }} - 1 ))
                    sudo docker compose down --remove-orphans
                    sudo docker compose pull ${{ vars.DOCKERHUB_USERNAME }}/${{env.IMAGE_NAME}}:$PREVIOUS_RUN_NUMBER
                    sudo docker compose up -d --force-recreate
                    echo "Reverted to previous image for run number: $PREVIOUS_RUN_NUMBER"